
#default port is 8761
server:
  port: 8761

#eureka config
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    registry-sync-retry-wait-ms: 3
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/







