eureka:
  instance:
    preferIpAddress: true
    appname: lincenseServer
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
server:
  port: 8001

redisConfig:
    server: localhost
    port: 6379

    #Setting the logging levels for the service
    logging:
      level:
        com.netflix: WARN
        org.springframework.web: WARN
        hx.springclouds.streams: DEBUG

