eureka:
  instance:
    preferIpAddress: true
    appname: lincenseServer
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
server:
  port: 8001

redisConfig:
    server: localhost
    port: 6379

