server:
  port: 9000

eureka:
  instance:
    preferIpAddress: true
    appname: zuulservice
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/



spring:
  application:
    name: zuulservice
  profiles:
    active: default



